name: Publish Package to NPM and Cloudflare

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 1.0.1)'
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test
      
      - name: Build
        run: npm run build
      
      - name: Set version (for manual trigger)
        if: github.event_name == 'workflow_dispatch'
        run: npm version ${{ github.event.inputs.version }} --no-git-tag-version
      
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      # Prepare for Cloudflare R2 deployment
      - name: Create package for Cloudflare
        run: |
          mkdir -p cloudflare-package
          cp -r dist/* cloudflare-package/
          cp package.json cloudflare-package/
          cp README.md cloudflare-package/
      
      # Deploy to Cloudflare R2
      - name: Configure AWS credentials for Cloudflare R2
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CLOUDFLARE_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY }}
          aws-region: auto
          endpoint-url: https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com
      
      - name: Upload to Cloudflare R2
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          aws s3 sync cloudflare-package/ s3://${{ secrets.CLOUDFLARE_BUCKET_NAME }}/ghana-card-detector/${PACKAGE_VERSION}/
          # Also update latest version
          aws s3 sync cloudflare-package/ s3://${{ secrets.CLOUDFLARE_BUCKET_NAME }}/ghana-card-detector/latest/